spring:
  data:
    mongodb:
      host: ${MONGODB_IP:localhost}
      port: ${MONGODB_PORT:27017}
      username: ${MONGODB_USERNAME:test}
      password: ${MONGODB_PWD:test}
      database: ${MONGODB_DATABASE:test}